### ISSUE TITLE
ERROR! Please upload only a CSV file.

### ISSUE THREAD

**Issue by rahyarserver** [hexonet/whmcs-ispapi-pricingimporter#83]
From the Use a CSV file section
We can't upload the file at all
And it always gives the following error message

> ERROR!
> Please upload only one CSV file

The sample file used is also the files of the specified format
It always gives the same error message

 - Device: all device
 - OS: Windows
 - Browser : all Browser  ( chrom firefox .. )
 - WHMCS Version 7 - 7.8.3
 - PHP Version 5.6 - 7.3
 - ISPAPI Pricing Importer Module Version 4.0.4

**Comment by tulsi91** [comment]
Hello,

Unfortunately, uploading a CSV file using Windows do not work properly. We have this issue on our wish list to provide a fix. But I do not have an ETA on it.
I will contact you once I have any new update on it.

Best regards
Tulsi

**Comment by papakai** [comment]
Dear @rahyarserver 

could you please give v4.0.5 a try and let us know if that solves your issue?
https://github.com/hexonet/whmcs-ispapi-pricingimporter/raw/master/whmcs-ispapi-pricingimporter-latest.zip


FYI: There's a know issue with import of premium domains (standard price will be added instead of premium price). So if you want to import also premium domains, you will need to update item's price in database manually.

We are currently working on a revamp of this module, it will include patches for all known issues and also feature requests. No ETA available for that new version which will be launched as completely new module anyways.

**Comment by rahyarserver** [comment]
> Dear @rahyarserver
> 
> could you please give v4.0.5 a try and let us know if that solves your issue?
> https://github.com/hexonet/whmcs-ispapi-pricingimporter/raw/master/whmcs-ispapi-pricingimporter-latest.zip
> 
> FYI: There's a know issue with import of premium domains (standard price will be added instead of premium price). So if you want to import also premium domains, you will need to update item's price in database manually.
> 
> We are currently working on a revamp of this module, it will include patches for all known issues and also feature requests. No ETA available for that new version which will be launched as completely new module anyways.

This issue was fixed. 
thanks for your cooperation
